// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Park2API.Contexts;

namespace Park2API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210202112104_two")]
    partial class two
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Identity")
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("Park2API.Entities.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Hour")
                        .HasColumnType("int");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(16,4)");

                    b.Property<int>("WeekDay")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Discounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Hour = 0,
                            Rate = 1.0m,
                            WeekDay = 1
                        },
                        new
                        {
                            Id = 2,
                            Hour = 1,
                            Rate = 1.0m,
                            WeekDay = 1
                        },
                        new
                        {
                            Id = 3,
                            Hour = 2,
                            Rate = 1.0m,
                            WeekDay = 1
                        },
                        new
                        {
                            Id = 4,
                            Hour = 3,
                            Rate = 1.0m,
                            WeekDay = 1
                        },
                        new
                        {
                            Id = 5,
                            Hour = 4,
                            Rate = 1.0m,
                            WeekDay = 1
                        },
                        new
                        {
                            Id = 6,
                            Hour = 5,
                            Rate = 1.0m,
                            WeekDay = 1
                        },
                        new
                        {
                            Id = 7,
                            Hour = 6,
                            Rate = 1.0m,
                            WeekDay = 1
                        },
                        new
                        {
                            Id = 8,
                            Hour = 7,
                            Rate = 1.0m,
                            WeekDay = 1
                        },
                        new
                        {
                            Id = 9,
                            Hour = 8,
                            Rate = 1.0m,
                            WeekDay = 1
                        },
                        new
                        {
                            Id = 10,
                            Hour = 9,
                            Rate = 1.0m,
                            WeekDay = 1
                        },
                        new
                        {
                            Id = 11,
                            Hour = 10,
                            Rate = 1.0m,
                            WeekDay = 1
                        },
                        new
                        {
                            Id = 12,
                            Hour = 11,
                            Rate = 1.0m,
                            WeekDay = 1
                        },
                        new
                        {
                            Id = 13,
                            Hour = 12,
                            Rate = 1.0m,
                            WeekDay = 1
                        },
                        new
                        {
                            Id = 14,
                            Hour = 13,
                            Rate = 1.0m,
                            WeekDay = 1
                        },
                        new
                        {
                            Id = 15,
                            Hour = 14,
                            Rate = 1.0m,
                            WeekDay = 1
                        },
                        new
                        {
                            Id = 16,
                            Hour = 15,
                            Rate = 1.0m,
                            WeekDay = 1
                        },
                        new
                        {
                            Id = 17,
                            Hour = 16,
                            Rate = 1.0m,
                            WeekDay = 1
                        },
                        new
                        {
                            Id = 18,
                            Hour = 17,
                            Rate = 1.0m,
                            WeekDay = 1
                        },
                        new
                        {
                            Id = 19,
                            Hour = 18,
                            Rate = 1.0m,
                            WeekDay = 1
                        },
                        new
                        {
                            Id = 20,
                            Hour = 19,
                            Rate = 1.0m,
                            WeekDay = 1
                        },
                        new
                        {
                            Id = 21,
                            Hour = 20,
                            Rate = 1.0m,
                            WeekDay = 1
                        },
                        new
                        {
                            Id = 22,
                            Hour = 21,
                            Rate = 1.0m,
                            WeekDay = 1
                        },
                        new
                        {
                            Id = 23,
                            Hour = 22,
                            Rate = 1.0m,
                            WeekDay = 1
                        },
                        new
                        {
                            Id = 24,
                            Hour = 23,
                            Rate = 1.0m,
                            WeekDay = 1
                        },
                        new
                        {
                            Id = 25,
                            Hour = 0,
                            Rate = 1.0m,
                            WeekDay = 2
                        },
                        new
                        {
                            Id = 26,
                            Hour = 1,
                            Rate = 1.0m,
                            WeekDay = 2
                        },
                        new
                        {
                            Id = 27,
                            Hour = 2,
                            Rate = 1.0m,
                            WeekDay = 2
                        },
                        new
                        {
                            Id = 28,
                            Hour = 3,
                            Rate = 1.0m,
                            WeekDay = 2
                        },
                        new
                        {
                            Id = 29,
                            Hour = 4,
                            Rate = 1.0m,
                            WeekDay = 2
                        },
                        new
                        {
                            Id = 30,
                            Hour = 5,
                            Rate = 1.0m,
                            WeekDay = 2
                        },
                        new
                        {
                            Id = 31,
                            Hour = 6,
                            Rate = 1.0m,
                            WeekDay = 2
                        },
                        new
                        {
                            Id = 32,
                            Hour = 7,
                            Rate = 1.0m,
                            WeekDay = 2
                        },
                        new
                        {
                            Id = 33,
                            Hour = 8,
                            Rate = 1.0m,
                            WeekDay = 2
                        },
                        new
                        {
                            Id = 34,
                            Hour = 9,
                            Rate = 1.0m,
                            WeekDay = 2
                        },
                        new
                        {
                            Id = 35,
                            Hour = 10,
                            Rate = 1.0m,
                            WeekDay = 2
                        },
                        new
                        {
                            Id = 36,
                            Hour = 11,
                            Rate = 1.0m,
                            WeekDay = 2
                        },
                        new
                        {
                            Id = 37,
                            Hour = 12,
                            Rate = 1.0m,
                            WeekDay = 2
                        },
                        new
                        {
                            Id = 38,
                            Hour = 13,
                            Rate = 1.0m,
                            WeekDay = 2
                        },
                        new
                        {
                            Id = 39,
                            Hour = 14,
                            Rate = 1.0m,
                            WeekDay = 2
                        },
                        new
                        {
                            Id = 40,
                            Hour = 15,
                            Rate = 1.0m,
                            WeekDay = 2
                        },
                        new
                        {
                            Id = 41,
                            Hour = 16,
                            Rate = 1.0m,
                            WeekDay = 2
                        },
                        new
                        {
                            Id = 42,
                            Hour = 17,
                            Rate = 1.0m,
                            WeekDay = 2
                        },
                        new
                        {
                            Id = 43,
                            Hour = 18,
                            Rate = 1.0m,
                            WeekDay = 2
                        },
                        new
                        {
                            Id = 44,
                            Hour = 19,
                            Rate = 1.0m,
                            WeekDay = 2
                        },
                        new
                        {
                            Id = 45,
                            Hour = 20,
                            Rate = 1.0m,
                            WeekDay = 2
                        },
                        new
                        {
                            Id = 46,
                            Hour = 21,
                            Rate = 1.0m,
                            WeekDay = 2
                        },
                        new
                        {
                            Id = 47,
                            Hour = 22,
                            Rate = 1.0m,
                            WeekDay = 2
                        },
                        new
                        {
                            Id = 48,
                            Hour = 23,
                            Rate = 1.0m,
                            WeekDay = 2
                        },
                        new
                        {
                            Id = 49,
                            Hour = 0,
                            Rate = 1.0m,
                            WeekDay = 3
                        },
                        new
                        {
                            Id = 50,
                            Hour = 1,
                            Rate = 1.0m,
                            WeekDay = 3
                        },
                        new
                        {
                            Id = 51,
                            Hour = 2,
                            Rate = 1.0m,
                            WeekDay = 3
                        },
                        new
                        {
                            Id = 52,
                            Hour = 3,
                            Rate = 1.0m,
                            WeekDay = 3
                        },
                        new
                        {
                            Id = 53,
                            Hour = 4,
                            Rate = 1.0m,
                            WeekDay = 3
                        },
                        new
                        {
                            Id = 54,
                            Hour = 5,
                            Rate = 1.0m,
                            WeekDay = 3
                        },
                        new
                        {
                            Id = 55,
                            Hour = 6,
                            Rate = 1.0m,
                            WeekDay = 3
                        },
                        new
                        {
                            Id = 56,
                            Hour = 7,
                            Rate = 1.0m,
                            WeekDay = 3
                        },
                        new
                        {
                            Id = 57,
                            Hour = 8,
                            Rate = 1.0m,
                            WeekDay = 3
                        },
                        new
                        {
                            Id = 58,
                            Hour = 9,
                            Rate = 1.0m,
                            WeekDay = 3
                        },
                        new
                        {
                            Id = 59,
                            Hour = 10,
                            Rate = 1.0m,
                            WeekDay = 3
                        },
                        new
                        {
                            Id = 60,
                            Hour = 11,
                            Rate = 1.0m,
                            WeekDay = 3
                        },
                        new
                        {
                            Id = 61,
                            Hour = 12,
                            Rate = 1.0m,
                            WeekDay = 3
                        },
                        new
                        {
                            Id = 62,
                            Hour = 13,
                            Rate = 1.0m,
                            WeekDay = 3
                        },
                        new
                        {
                            Id = 63,
                            Hour = 14,
                            Rate = 1.0m,
                            WeekDay = 3
                        },
                        new
                        {
                            Id = 64,
                            Hour = 15,
                            Rate = 1.0m,
                            WeekDay = 3
                        },
                        new
                        {
                            Id = 65,
                            Hour = 16,
                            Rate = 1.0m,
                            WeekDay = 3
                        },
                        new
                        {
                            Id = 66,
                            Hour = 17,
                            Rate = 1.0m,
                            WeekDay = 3
                        },
                        new
                        {
                            Id = 67,
                            Hour = 18,
                            Rate = 1.0m,
                            WeekDay = 3
                        },
                        new
                        {
                            Id = 68,
                            Hour = 19,
                            Rate = 1.0m,
                            WeekDay = 3
                        },
                        new
                        {
                            Id = 69,
                            Hour = 20,
                            Rate = 1.0m,
                            WeekDay = 3
                        },
                        new
                        {
                            Id = 70,
                            Hour = 21,
                            Rate = 1.0m,
                            WeekDay = 3
                        },
                        new
                        {
                            Id = 71,
                            Hour = 22,
                            Rate = 1.0m,
                            WeekDay = 3
                        },
                        new
                        {
                            Id = 72,
                            Hour = 23,
                            Rate = 1.0m,
                            WeekDay = 3
                        },
                        new
                        {
                            Id = 73,
                            Hour = 0,
                            Rate = 1.0m,
                            WeekDay = 4
                        },
                        new
                        {
                            Id = 74,
                            Hour = 1,
                            Rate = 1.0m,
                            WeekDay = 4
                        },
                        new
                        {
                            Id = 75,
                            Hour = 2,
                            Rate = 1.0m,
                            WeekDay = 4
                        },
                        new
                        {
                            Id = 76,
                            Hour = 3,
                            Rate = 1.0m,
                            WeekDay = 4
                        },
                        new
                        {
                            Id = 77,
                            Hour = 4,
                            Rate = 1.0m,
                            WeekDay = 4
                        },
                        new
                        {
                            Id = 78,
                            Hour = 5,
                            Rate = 1.0m,
                            WeekDay = 4
                        },
                        new
                        {
                            Id = 79,
                            Hour = 6,
                            Rate = 1.0m,
                            WeekDay = 4
                        },
                        new
                        {
                            Id = 80,
                            Hour = 7,
                            Rate = 1.0m,
                            WeekDay = 4
                        },
                        new
                        {
                            Id = 81,
                            Hour = 8,
                            Rate = 1.0m,
                            WeekDay = 4
                        },
                        new
                        {
                            Id = 82,
                            Hour = 9,
                            Rate = 1.0m,
                            WeekDay = 4
                        },
                        new
                        {
                            Id = 83,
                            Hour = 10,
                            Rate = 1.0m,
                            WeekDay = 4
                        },
                        new
                        {
                            Id = 84,
                            Hour = 11,
                            Rate = 1.0m,
                            WeekDay = 4
                        },
                        new
                        {
                            Id = 85,
                            Hour = 12,
                            Rate = 1.0m,
                            WeekDay = 4
                        },
                        new
                        {
                            Id = 86,
                            Hour = 13,
                            Rate = 1.0m,
                            WeekDay = 4
                        },
                        new
                        {
                            Id = 87,
                            Hour = 14,
                            Rate = 1.0m,
                            WeekDay = 4
                        },
                        new
                        {
                            Id = 88,
                            Hour = 15,
                            Rate = 1.0m,
                            WeekDay = 4
                        },
                        new
                        {
                            Id = 89,
                            Hour = 16,
                            Rate = 1.0m,
                            WeekDay = 4
                        },
                        new
                        {
                            Id = 90,
                            Hour = 17,
                            Rate = 1.0m,
                            WeekDay = 4
                        },
                        new
                        {
                            Id = 91,
                            Hour = 18,
                            Rate = 1.0m,
                            WeekDay = 4
                        },
                        new
                        {
                            Id = 92,
                            Hour = 19,
                            Rate = 1.0m,
                            WeekDay = 4
                        },
                        new
                        {
                            Id = 93,
                            Hour = 20,
                            Rate = 1.0m,
                            WeekDay = 4
                        },
                        new
                        {
                            Id = 94,
                            Hour = 21,
                            Rate = 1.0m,
                            WeekDay = 4
                        },
                        new
                        {
                            Id = 95,
                            Hour = 22,
                            Rate = 1.0m,
                            WeekDay = 4
                        },
                        new
                        {
                            Id = 96,
                            Hour = 23,
                            Rate = 1.0m,
                            WeekDay = 4
                        },
                        new
                        {
                            Id = 97,
                            Hour = 0,
                            Rate = 1.0m,
                            WeekDay = 5
                        },
                        new
                        {
                            Id = 98,
                            Hour = 1,
                            Rate = 1.0m,
                            WeekDay = 5
                        },
                        new
                        {
                            Id = 99,
                            Hour = 2,
                            Rate = 1.0m,
                            WeekDay = 5
                        },
                        new
                        {
                            Id = 100,
                            Hour = 3,
                            Rate = 1.0m,
                            WeekDay = 5
                        },
                        new
                        {
                            Id = 101,
                            Hour = 4,
                            Rate = 1.0m,
                            WeekDay = 5
                        },
                        new
                        {
                            Id = 102,
                            Hour = 5,
                            Rate = 1.0m,
                            WeekDay = 5
                        },
                        new
                        {
                            Id = 103,
                            Hour = 6,
                            Rate = 1.0m,
                            WeekDay = 5
                        },
                        new
                        {
                            Id = 104,
                            Hour = 7,
                            Rate = 1.0m,
                            WeekDay = 5
                        },
                        new
                        {
                            Id = 105,
                            Hour = 8,
                            Rate = 1.0m,
                            WeekDay = 5
                        },
                        new
                        {
                            Id = 106,
                            Hour = 9,
                            Rate = 1.0m,
                            WeekDay = 5
                        },
                        new
                        {
                            Id = 107,
                            Hour = 10,
                            Rate = 1.0m,
                            WeekDay = 5
                        },
                        new
                        {
                            Id = 108,
                            Hour = 11,
                            Rate = 1.0m,
                            WeekDay = 5
                        },
                        new
                        {
                            Id = 109,
                            Hour = 12,
                            Rate = 1.0m,
                            WeekDay = 5
                        },
                        new
                        {
                            Id = 110,
                            Hour = 13,
                            Rate = 1.0m,
                            WeekDay = 5
                        },
                        new
                        {
                            Id = 111,
                            Hour = 14,
                            Rate = 1.0m,
                            WeekDay = 5
                        },
                        new
                        {
                            Id = 112,
                            Hour = 15,
                            Rate = 1.0m,
                            WeekDay = 5
                        },
                        new
                        {
                            Id = 113,
                            Hour = 16,
                            Rate = 1.0m,
                            WeekDay = 5
                        },
                        new
                        {
                            Id = 114,
                            Hour = 17,
                            Rate = 1.0m,
                            WeekDay = 5
                        },
                        new
                        {
                            Id = 115,
                            Hour = 18,
                            Rate = 1.0m,
                            WeekDay = 5
                        },
                        new
                        {
                            Id = 116,
                            Hour = 19,
                            Rate = 1.0m,
                            WeekDay = 5
                        },
                        new
                        {
                            Id = 117,
                            Hour = 20,
                            Rate = 1.0m,
                            WeekDay = 5
                        },
                        new
                        {
                            Id = 118,
                            Hour = 21,
                            Rate = 1.0m,
                            WeekDay = 5
                        },
                        new
                        {
                            Id = 119,
                            Hour = 22,
                            Rate = 1.0m,
                            WeekDay = 5
                        },
                        new
                        {
                            Id = 120,
                            Hour = 23,
                            Rate = 1.0m,
                            WeekDay = 5
                        },
                        new
                        {
                            Id = 121,
                            Hour = 0,
                            Rate = 1.0m,
                            WeekDay = 6
                        },
                        new
                        {
                            Id = 122,
                            Hour = 1,
                            Rate = 1.0m,
                            WeekDay = 6
                        },
                        new
                        {
                            Id = 123,
                            Hour = 2,
                            Rate = 1.0m,
                            WeekDay = 6
                        },
                        new
                        {
                            Id = 124,
                            Hour = 3,
                            Rate = 1.0m,
                            WeekDay = 6
                        },
                        new
                        {
                            Id = 125,
                            Hour = 4,
                            Rate = 1.0m,
                            WeekDay = 6
                        },
                        new
                        {
                            Id = 126,
                            Hour = 5,
                            Rate = 1.0m,
                            WeekDay = 6
                        },
                        new
                        {
                            Id = 127,
                            Hour = 6,
                            Rate = 1.0m,
                            WeekDay = 6
                        },
                        new
                        {
                            Id = 128,
                            Hour = 7,
                            Rate = 1.0m,
                            WeekDay = 6
                        },
                        new
                        {
                            Id = 129,
                            Hour = 8,
                            Rate = 1.0m,
                            WeekDay = 6
                        },
                        new
                        {
                            Id = 130,
                            Hour = 9,
                            Rate = 1.0m,
                            WeekDay = 6
                        },
                        new
                        {
                            Id = 131,
                            Hour = 10,
                            Rate = 1.0m,
                            WeekDay = 6
                        },
                        new
                        {
                            Id = 132,
                            Hour = 11,
                            Rate = 1.0m,
                            WeekDay = 6
                        },
                        new
                        {
                            Id = 133,
                            Hour = 12,
                            Rate = 1.0m,
                            WeekDay = 6
                        },
                        new
                        {
                            Id = 134,
                            Hour = 13,
                            Rate = 1.0m,
                            WeekDay = 6
                        },
                        new
                        {
                            Id = 135,
                            Hour = 14,
                            Rate = 1.0m,
                            WeekDay = 6
                        },
                        new
                        {
                            Id = 136,
                            Hour = 15,
                            Rate = 1.0m,
                            WeekDay = 6
                        },
                        new
                        {
                            Id = 137,
                            Hour = 16,
                            Rate = 1.0m,
                            WeekDay = 6
                        },
                        new
                        {
                            Id = 138,
                            Hour = 17,
                            Rate = 1.0m,
                            WeekDay = 6
                        },
                        new
                        {
                            Id = 139,
                            Hour = 18,
                            Rate = 1.0m,
                            WeekDay = 6
                        },
                        new
                        {
                            Id = 140,
                            Hour = 19,
                            Rate = 1.0m,
                            WeekDay = 6
                        },
                        new
                        {
                            Id = 141,
                            Hour = 20,
                            Rate = 1.0m,
                            WeekDay = 6
                        },
                        new
                        {
                            Id = 142,
                            Hour = 21,
                            Rate = 1.0m,
                            WeekDay = 6
                        },
                        new
                        {
                            Id = 143,
                            Hour = 22,
                            Rate = 1.0m,
                            WeekDay = 6
                        },
                        new
                        {
                            Id = 144,
                            Hour = 23,
                            Rate = 1.0m,
                            WeekDay = 6
                        },
                        new
                        {
                            Id = 145,
                            Hour = 0,
                            Rate = 1.0m,
                            WeekDay = 0
                        },
                        new
                        {
                            Id = 146,
                            Hour = 1,
                            Rate = 1.0m,
                            WeekDay = 0
                        },
                        new
                        {
                            Id = 147,
                            Hour = 2,
                            Rate = 1.0m,
                            WeekDay = 0
                        },
                        new
                        {
                            Id = 148,
                            Hour = 3,
                            Rate = 1.0m,
                            WeekDay = 0
                        },
                        new
                        {
                            Id = 149,
                            Hour = 4,
                            Rate = 1.0m,
                            WeekDay = 0
                        },
                        new
                        {
                            Id = 150,
                            Hour = 5,
                            Rate = 1.0m,
                            WeekDay = 0
                        },
                        new
                        {
                            Id = 151,
                            Hour = 6,
                            Rate = 1.0m,
                            WeekDay = 0
                        },
                        new
                        {
                            Id = 152,
                            Hour = 7,
                            Rate = 1.0m,
                            WeekDay = 0
                        },
                        new
                        {
                            Id = 153,
                            Hour = 8,
                            Rate = 1.0m,
                            WeekDay = 0
                        },
                        new
                        {
                            Id = 154,
                            Hour = 9,
                            Rate = 1.0m,
                            WeekDay = 0
                        },
                        new
                        {
                            Id = 155,
                            Hour = 10,
                            Rate = 1.0m,
                            WeekDay = 0
                        },
                        new
                        {
                            Id = 156,
                            Hour = 11,
                            Rate = 1.0m,
                            WeekDay = 0
                        },
                        new
                        {
                            Id = 157,
                            Hour = 12,
                            Rate = 1.0m,
                            WeekDay = 0
                        },
                        new
                        {
                            Id = 158,
                            Hour = 13,
                            Rate = 1.0m,
                            WeekDay = 0
                        },
                        new
                        {
                            Id = 159,
                            Hour = 14,
                            Rate = 1.0m,
                            WeekDay = 0
                        },
                        new
                        {
                            Id = 160,
                            Hour = 15,
                            Rate = 1.0m,
                            WeekDay = 0
                        },
                        new
                        {
                            Id = 161,
                            Hour = 16,
                            Rate = 1.0m,
                            WeekDay = 0
                        },
                        new
                        {
                            Id = 162,
                            Hour = 17,
                            Rate = 1.0m,
                            WeekDay = 0
                        },
                        new
                        {
                            Id = 163,
                            Hour = 18,
                            Rate = 1.0m,
                            WeekDay = 0
                        },
                        new
                        {
                            Id = 164,
                            Hour = 19,
                            Rate = 1.0m,
                            WeekDay = 0
                        },
                        new
                        {
                            Id = 165,
                            Hour = 20,
                            Rate = 1.0m,
                            WeekDay = 0
                        },
                        new
                        {
                            Id = 166,
                            Hour = 21,
                            Rate = 1.0m,
                            WeekDay = 0
                        },
                        new
                        {
                            Id = 167,
                            Hour = 22,
                            Rate = 1.0m,
                            WeekDay = 0
                        },
                        new
                        {
                            Id = 168,
                            Hour = 23,
                            Rate = 1.0m,
                            WeekDay = 0
                        });
                });

            modelBuilder.Entity("Park2API.Entities.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("SlotId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("TimeEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TimeStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(16,4)");

                    b.HasKey("Id");

                    b.HasIndex("SlotId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Park2API.Entities.Slot", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("PricePerHour")
                        .HasColumnType("decimal(16,4)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Slots");

                    b.HasData(
                        new
                        {
                            Id = "A01",
                            PricePerHour = 0m,
                            Status = "Reserved"
                        },
                        new
                        {
                            Id = "A02",
                            PricePerHour = 0m,
                            Status = "Reserved"
                        },
                        new
                        {
                            Id = "A03",
                            PricePerHour = 2.15m,
                            Status = "Available"
                        },
                        new
                        {
                            Id = "A04",
                            PricePerHour = 2.15m,
                            Status = "Available"
                        },
                        new
                        {
                            Id = "A05",
                            PricePerHour = 2.15m,
                            Status = "Available"
                        },
                        new
                        {
                            Id = "B01",
                            PricePerHour = 0.50m,
                            Status = "Hotel"
                        },
                        new
                        {
                            Id = "B02",
                            PricePerHour = 0.50m,
                            Status = "Reserved"
                        },
                        new
                        {
                            Id = "B03",
                            PricePerHour = 1.90m,
                            Status = "Available"
                        },
                        new
                        {
                            Id = "B04",
                            PricePerHour = 1.90m,
                            Status = "Available"
                        },
                        new
                        {
                            Id = "B05",
                            PricePerHour = 1.90m,
                            Status = "Available"
                        });
                });

            modelBuilder.Entity("Park2API.Entities.Status", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Status");

                    b.HasData(
                        new
                        {
                            Id = "Reserved",
                            Description = "Slot reserved for internal use."
                        },
                        new
                        {
                            Id = "Available",
                            Description = "Slot available for external booking."
                        },
                        new
                        {
                            Id = "Hotel",
                            Description = "Slot reserved for Hotel use only."
                        });
                });

            modelBuilder.Entity("Park2API.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Park2API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Park2API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Park2API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Park2API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Park2API.Entities.Reservation", b =>
                {
                    b.HasOne("Park2API.Entities.Slot", "Slot")
                        .WithMany()
                        .HasForeignKey("SlotId");

                    b.HasOne("Park2API.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("ApplicationUser");

                    b.Navigation("Slot");
                });
#pragma warning restore 612, 618
        }
    }
}
